# Generated by Django 4.1.7 on 2023-03-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_project_created_project_datecompleted_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='idProject',
            new_name='project',
        ),
    ]
